version: '3.7'

services:
  mcro-profile-db:
    container_name: mcro-profile-postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcro_db
    networks:
      - node-bridge-network

networks:
  socket-network:
  node-bridge-network:
    driver: bridge
volumes:
  socket-pgdata:
